src/objects/Sell_Item__c.object
<CustomObject>
    <fields>
        <fullName>Price_Type__c</fullName>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct Price</fullName>
                </value>
                <value>
                    <fullName>Advanced Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sell Item</label>
    <nameField>
        <label>Sell Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SellItemService.cls
public with sharing class SellItemService {

    public void calculatePricesForGivenItems(final List<Sell_Item__c> sellItems) {
        Map<String, IPriceCalculatorService> services = new PriceCalculatorInjector().getPriceCalculators();

        for (Sell_Item__c sellItem : sellItems) {
            IPriceCalculatorService priceService = services.containsKey(sellItem.Price_Type__c)
                ? services.get(sellItem.Price_Type__c)
                : services.get('Default');

            if (null == priceService) {
                throw new SellItemServiceException('Price Calculator was not found!');
            }
            priceService.calculatePrice(sellItem);
        }
    }

    public class SellItemServiceException extends Exception {}
}