src/objects/Sell_Item__c.object
<CustomObject>
    <fields>
        <fullName>Initial_Cost__c</fullName>
        <label>Initial Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parameter_A__c</fullName>
        <label>Parameter A</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parameter_B__c</fullName>
        <label>Parameter B</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sell Item</label>
    <nameField>
        <label>Sell Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdvancedPriceCalculator.cls
public with sharing class AdvancedPriceCalculator implements IPriceCalculatorService{

    public void calculatePrice(final Sell_Item__c sellItem) {

        Boolean isCheckPassed = true;
        Set<String> fieldsToCheck = new Set<String> {'Parameter_A__c', 'Parameter_B__c', 'Initial_Cost__c'};

        for (String sellItemField : fieldsToCheck) {
            if (null == sellItem.get(sellItemField)) {
                sellItem.addError(sellItemField, 'Cannot be blank during Advanced Price Calculation!');
                isCheckPassed = false;
            }
        }

        if (isCheckPassed) {
            sellItem.Price__c = sellItem.Initial_Cost__c + 0.25 * sellItem.Parameter_A__c + (sellItem.Parameter_A__c * sellItem.Parameter_B__c);
        }
    }
}